import type { LunarFeature } from './types';

export const LUNAR_FEATURES: LunarFeature[] = [
  { name: 'Tycho', lat: 43.37, lon: -11.35, type: 'Crater', description: 'Prominent crater with ray system, 85km diameter' },
  { name: 'Copernicus', lat: 9.62, lon: -20.08, type: 'Crater', description: 'Major impact crater, 93km diameter, visible rays' },
  { name: 'Aristarchus', lat: 23.73, lon: -47.49, type: 'Crater', description: 'Bright crater, 40km diameter, strongest reflectance' },
  { name: 'Kepler', lat: 32.08, lon: -38.01, type: 'Crater', description: 'Impact crater, 32km diameter' },
  { name: 'Plato', lat: 51.62, lon: -9.38, type: 'Crater', description: 'Large crater, 101km diameter, dark floor' },
  { name: 'Aristoteles', lat: 50.22, lon: 21.45, type: 'Crater', description: 'Large crater, 87km diameter' },
  { name: 'Euler', lat: 22.07, lon: -29.18, type: 'Crater', description: 'Impact crater, 27km diameter' },
  { name: 'Gassendi', lat: -17.55, lon: -39.97, type: 'Crater', description: 'Large crater, 80km diameter, floor fractured' },
  { name: 'Grimaldi', lat: -5.48, lon: -68.64, type: 'Crater', description: 'Crater with dark floor, 124km diameter' },
  { name: 'Langrenus', lat: -8.95, lon: 60.91, type: 'Crater', description: 'Large crater, 132km diameter' },
  { name: 'Petavius', lat: -27.11, lon: 26.09, type: 'Crater', description: 'Large crater, 165km diameter' },
  { name: 'Piccolomini', lat: -29.75, lon: 32.55, type: 'Crater', description: 'Crater with mountain peak, 88km diameter' },
  { name: 'Schickard', lat: -44.44, lon: -55.58, type: 'Crater', description: 'Large crater, 227km diameter' },
  { name: 'Theophilus', lat: -11.42, lon: 26.36, type: 'Crater', description: 'Impact crater, 98km diameter' },
  { name: 'Cleomedes', lat: 27.72, lon: 56.77, type: 'Crater', description: 'Large crater, 126km diameter' },
  { name: 'Endymion', lat: 53.62, lon: 57.73, type: 'Crater', description: 'Large crater, 122km diameter' },
  { name: 'Mare Crisium', lat: 17.0, lon: 59.1, type: 'Mare', description: 'Sea of Crises, prominent dark mare' },
  { name: 'Mare Tranquillitatis', lat: 8.5, lon: 31.4, type: 'Mare', description: 'Sea of Tranquility, Apollo 11 landing site' },
  { name: 'Mare Imbrium', lat: 32.8, lon: -15.2, type: 'Mare', description: 'Sea of Rains, largest nearside mare' },
  { name: 'Mare Serenitatis', lat: 28.0, lon: 17.5, type: 'Mare', description: 'Sea of Serenity' },
  { name: 'Mare Fecunditatis', lat: -1.4, lon: 51.3, type: 'Mare', description: 'Sea of Fertility' },
  { name: 'Mare Nubium', lat: -21.0, lon: -17.0, type: 'Mare', description: 'Sea of Clouds' },
  { name: 'Shackleton', lat: -89.63, lon: 126.27, type: 'Crater', description: 'South pole crater, permanently shadowed' },
  { name: 'South Pole-Aitken Basin', lat: -53.0, lon: -169.0, type: 'Basin', description: 'Largest known impact basin, 2,500km diameter' },
  { name: 'Oceanus Procellarum', lat: 18.0, lon: -15.0, type: 'Mare', description: 'Ocean of Storms, largest mare' },
];
